Q1) Introduction of PyTorch Tensors and Basic Operations.

a. To understand PyTorch tensors, their initialization methods, and data types.

In [ ]:
# run on colab
import torch
import numpy as np
import sys # Import the sys module
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])
c=torch.tensor([100,200,300],dtype=torch.int32)
print(a)
print(b)
print(c)

tensor([1, 2, 3, 4])
tensor([5, 6, 7, 8])
tensor([100, 200, 300], dtype=torch.int32)


b. To perform tensor operations such as arithmetic, broadcasting, indexing, and
reshaping.

In [2]:
#arithmatic
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])

print(x+y)

#broadcasting
z=torch.tensor([9,10])
print(x+z)

#indexing
print(z[1])

#reshaping
r = torch.arange(6)
print(r.reshape(2, 3))

tensor([[ 6,  8],
        [10, 12]])
tensor([[10, 12],
        [12, 14]])
tensor(10)
tensor([[0, 1, 2],
        [3, 4, 5]])


c. To explore automatic differentiation using PyTorch’s Autograd system.

In [3]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1

y.backward()
print(x.grad)

tensor(7.)


Q2) Perform all linear algebra operation with Tensorflow.

In [5]:
import tensorflow as tf

A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Addition
print(A + B)

# Matrix multiplication
print(tf.matmul(A, B))

# Transpose
print(tf.transpose(A))

# Determinant
print(tf.linalg.det(A))

# Inverse
print(tf.linalg.inv(A))

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


Q3) Write a program to implement AND OR gates using Perceptron.

In [6]:
import numpy as np

def perceptron(x, w, b):
    return 1 if np.dot(x, w) + b >= 0 else 0

# AND gate
w_and = [1, 1]
b_and = -1.5

# OR gate
w_or = [1, 1]
b_or = -0.5

inputs = [(0,0),(0,1),(1,0),(1,1)]

print("AND Gate")
for i in inputs:
    print(i, perceptron(i, w_and, b_and))

print("\nOR Gate")
for i in inputs:
    print(i, perceptron(i, w_or, b_or))


AND Gate
(0, 0) 0
(0, 1) 0
(1, 0) 0
(1, 1) 1

OR Gate
(0, 0) 0
(0, 1) 1
(1, 0) 1
(1, 1) 1


Q4) Implementation of XOR Problem using PyTorch Neural Network.

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim

# Data
X = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32)

# Model
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training
for epoch in range(2000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

# Testing
print("XOR Output:")
print(model(X).round())


XOR Output:
tensor([[0.],
        [1.],
        [0.],
        [0.]], grad_fn=<RoundBackward0>)


Q5) Implement Simple below Neural Network to solve regression problem.

In [8]:
import torch
import torch.nn as nn
import torch.optim as optim

# Dummy data
X = torch.unsqueeze(torch.linspace(-10, 10, 100), dim=1)
y = X * 2 + 1

# Model
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(1, 2)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        return self.output(x)

model = SimpleNN()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training
for epoch in range(1000):
    optimizer.zero_grad()
    pred = model(X)
    loss = criterion(pred, y)
    loss.backward()
    optimizer.step()

print("Training completed")


Training completed
